In [1]:
# Import the needed libraries
import numpy as np

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [2]:
a = np.random.random((10, 10))
a_min = np.min(a)
a_max = np.max(a)

print(a)
print("Min Value:", a_min)
print("Max Value:", a_max)

[[0.33321335 0.44826989 0.51784648 0.46596472 0.08876517 0.81271065
  0.51206886 0.19205676 0.01967848 0.85449038]
 [0.87877945 0.45513552 0.25798999 0.78708472 0.88382055 0.15057063
  0.72128784 0.11917795 0.44057374 0.16482555]
 [0.51825335 0.68958065 0.16477142 0.06229627 0.79867263 0.51417698
  0.14347661 0.32572298 0.31762304 0.17371045]
 [0.57266401 0.41026702 0.01311318 0.69704348 0.48914712 0.85591432
  0.83588548 0.78750785 0.82621102 0.356612  ]
 [0.39714204 0.00933852 0.08395609 0.67733535 0.93852296 0.59302378
  0.92386068 0.58506155 0.76523052 0.81211629]
 [0.5557695  0.53682003 0.82839903 0.1569361  0.85871772 0.12385861
  0.28925943 0.97600394 0.4509451  0.26677603]
 [0.19505629 0.87054641 0.85303311 0.06277168 0.8369626  0.13275488
  0.61200328 0.06019404 0.18321862 0.34739457]
 [0.03761045 0.62743839 0.83790124 0.86236033 0.5871162  0.65676915
  0.07679493 0.39302097 0.32068525 0.65779129]
 [0.20369325 0.70472383 0.37383412 0.06035054 0.32609265 0.96945322
  0.51483987

**15. Create a 2d array with 1 on the border and 0 inside**

In [3]:
a = np.ones((10,10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
